MainProject/MainApp/urls.py
from django.urls import path
from .views import home_page_view

urlpatterns = [
    path('', home_page_view, name='index'),

    path('', home_page_view, name='about'),
    path('', home_page_view, name='about'),
    path('', home_page_view, name='services'),
    path('', home_page_view, name='portfolio-1'),
    path('', home_page_view, name='single-project'),
    path('', home_page_view, name='single-project-2'),
    path('', home_page_view, name='single-post'),
    path('', home_page_view, name='contact'),
]

MainProject/MainProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('MainApp.urls')),
    path('account/', include('account.urls', namespace='account')),
    # path('account/', include('account.urls'), namespace='account'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainProject/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import account_page_view, login_page_view, logout_view, register_page_view

app_name = 'account'

urlpatterns = [
    path('<int:user_id>/', account_page_view, name='view'),

    path('login/', login_page_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_page_view, name='register'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password_reset/password_change.html'), name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),
]

MainProject/MainApp/models.py
from django.db import models

# Create your models here.

MainProject/MainApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def home_page_view(request):
    template = 'MainApp/index.html'
    return render(request, template)

MainProject/templates/MainApp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>DarishkaAMS Agency Service</title>
	<!-- META TAGS -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'MainApp/img/favicon.png' %}">
<!--	<meta name="author" content="Amine Akhouad">-->
<!--	<meta name="description" content="AKAD is a creative and modern template for digital agencies">-->

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'MainApp/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'MainApp/css/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'MainApp/css/flexslider.css' %}">
	<link rel="stylesheet" href="{% static 'MainApp/css/animsition.min.css' %}">
	<link rel="stylesheet" href="{% static 'MainApp/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'MainApp/css/style.css' %}">
</head>
<body class="animsition">
	<!-- HEADER  -->
	<header class="main-header">
		<div class="container">
			<div class="logo">
				Welcome {{ user.username }}
<!--				<a href="{% url 'index' %}"><img src="{% static 'MainApp/img/darishkaams_nametag.png' %}" alt="logo" width="10" height="10" ></a>-->
			</div>
			<div class="menu">
				<!-- desktop navbar -->
				<nav class="desktop-nav">
					<ul class="first-level">
						{% if request.user.is_authenticated %}
						<li><a href="{% url 'index' %}" class="animsition-link">Home</a></li>
						<li><a href="{% url 'about' %}" class="animsition-link">about us</a></li>
						<li><a href="{% url 'account:view' user_id=request.user.id %}" class="animsition-link">Account</a></li>
						<li><a href="#">portfolio</a>
							<ul class="second-level">
								<li><a href="{% url 'portfolio-1' %}" class="animsition-link">portfolio list</a></li>
								<li><a href="{% url 'single-project' %}" class="animsition-link">single project 1</a></li>
								<li><a href="{% url 'single-project-2' %}" class="animsition-link">single project 2</a></li>
							</ul>
						</li>
						<li><a href="{% url 'account:logout' %}">logout</a>
						</li>
						<li><a href="{% url 'contact' %}" class="animsition-link">contact us</a></li>
						{% else %}
						<li><a href="{% url 'account:login' %}">login</a>
						</li>
						<li><a href="{% url 'account:register' %}">register</a>
						</li>
						{% endif %}
					</ul>
				</nav>
				<!-- mobile navbar -->
				<nav class="mobile-nav"></nav>
				<div class="menu-icon">
					<div class="line"></div>
					<div class="line"></div>
					<div class="line"></div>
				</div>
			</div>
		</div>
	</header>
	{% block content %}
		Replace this content
	{% endblock %}
	<!-- FOOTER -->
	<footer class="main-footer wow fadeInUp">
		<div class="container">
			<div class="col-md-8 col-sm-12">
				<div class="row">
					<nav class="footer-nav">
						<ul>
							{% if request.user.is_authenticated %}
							<li><a href="{% url 'index' %}" class="animsition-link link">Home</a></li>
							<li><a href="{% url 'about' %}" class="animsition-link link">about us</a></li>
							<li><a href="{% url 'account:view' user_id=request.user.id %}" class="animsition-link link">Account</a></li>
							<li><a href="{% url 'portfolio-1' %}" class="animsition-link link">portfolio</a></li>
							<li><a href="{% url 'account:logout' %}" class="animsition-link link">logout</a></li>
							<li><a href="{% url 'contact' %}" class="animsition-link link">contact us</a></li>
							{% else %}
							<li><a href="{% url 'account:login' %}" class="animsition-link link">login</a></li>
							<li><a href="{% url 'account:register' %}" class="animsition-link link">Register</a></li>
							{% endif %}
						</ul>
					</nav>
				</div>
			</div>

			<div class="col-md-4 col-sm-12" style="text-align:right">
				<div class="row">
					<div class="uppercase gray-text">
						created by DarishkaAMS and Akhouad
					</div>
					<ul class="social-icons" style="margin-top:30px;float:right">
						<li><a href="#"><i class="icon ion-social-facebook"></i></a></li>
						<li><a href="#"><i class="icon ion-social-twitter"></i></a></li>
						<li><a href="#"><i class="icon ion-social-youtube"></i></a></li>
						<li><a href="#"><i class="icon ion-social-linkedin"></i></a></li>
						<li><a href="#"><i class="icon ion-social-pinterest"></i></a></li>
						<li><a href="#"><i class="icon ion-social-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- SCRIPTS -->
	<script type="text/javascript" src="{% static 'MainApp/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'MainApp/js/isotope.pkgd.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'MainApp/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript" src="{% static 'MainApp/js/smoothScroll.js' %}"></script>
	<script type="text/javascript" src="{% static 'MainApp/js/jquery.animsition.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'MainApp/js/wow.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'MainApp/js/main.js' %}"></script>

	<script type="text/javascript" charset="utf-8">
		$(window).load(function() {
			new WOW().init();

			// initialise flexslider
			$('.site-hero').flexslider({
				animation: "fade",
				directionNav: false,
				controlNav: false,
				keyboardNav: true,
				slideToStart: 0,
				animationLoop: true,
				pauseOnHover: false,
				slideshowSpeed: 4000,
			});


			// initialize isotope
			var $container = $('.portfolio_container');
			$container.isotope({
				filter: '*',
			});

			$('.portfolio_filter a').click(function(){
				$('.portfolio_filter .active').removeClass('active');
				$(this).addClass('active');

				var selector = $(this).attr('data-filter');
				$container.isotope({
					filter: selector,
					animationOptions: {
						duration: 500,
						animationEngine : "jquery"
					}
				});
				return false;
			});
		});
	</script>
</body>
</html>

MainProject/templates/MainApp/blog-1.html
<!DOCTYPE html>
<html>
<head>
	<title>Blog - AKAD - Creative Digital Agency HTML Template</title>
	<!-- META TAGS -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">
	<meta name="author" content="Amine Akhouad">
	<meta name="description" content="AKAD is a creative and modern template for digital agencies">

	<!-- STYLES -->
	<link rel="stylesheet" href="assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="assets/css/ionicons.min.css">
	<link rel="stylesheet" href="assets/css/animsition.min.css">
	<link rel="stylesheet" href="assets/css/animate.css">
	<link rel="stylesheet" href="assets/css/style.css">
</head>
<body class="animsition">
	<!-- HEADER  -->
	<header class="main-header">
		<div class="container">
			<div class="logo">
				<a href="index.html"><img src="assets/img/logo.png" alt="logo"></a>
			</div>
			<div class="menu">
				<!-- desktop navbar -->
				<nav class="desktop-nav">
					<ul class="first-level">
						<li><a href="index.html" class="animsition-link">Home</a></li>
						<li><a href="about.html" class="animsition-link">about us</a></li>
						<li><a href="services.html" class="animsition-link">services</a></li>
						<li><a href="">portfolio</a>
							<ul class="second-level">
								<li><a href="portfolio-1.html" class="animsition-link">portfolio list</a></li>
								<li><a href="single-project.html" class="animsition-link">single project 1</a></li>
								<li><a href="single-project-2.html" class="animsition-link">single project 2</a></li>
							</ul>
						</li>
						<li><a href="">blog</a>
							<ul class="second-level">
								<li><a href="blog-1.html" class="animsition-link">posts list</a></li>
								<li><a href="single-post.html" class="animsition-link">single post</a></li>
							</ul>
						</li>
						<li><a href="contact.html" class="animsition-link">contact us</a></li>
					</ul>
				</nav>
				<!-- mobile navbar -->
				<nav class="mobile-nav"></nav>
				<div class="menu-icon">
					<div class="line"></div>
					<div class="line"></div>
					<div class="line"></div>
				</div>
			</div>
		</div>
	</header>

	<!-- HERO SECTION  -->
	<div class="site-hero_2">
		<div class="page-title">
			<div class="big-title montserrat-text uppercase">blog posts</div>
			<div class="small-title montserrat-text uppercase">home / blog</div>
		</div>
	</div>


	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-9 col-sm-12">
					<!-- blog post -->
					<div class="blog_post">
						<div class="post_media">
							<img src="assets/img/post_1.jpg" alt="post image">
						</div>
						<div class="post_info">
							<div class="post_date montserrat-text uppercase">january 13, 2016</div>
							<i class="icon ion-chatbox-working"></i>
							<span>8</span>
							<i class="icon ion-ios-heart"></i>
							<span>15</span>
						</div>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
						</p>
						<a href="single-post.html" class="link montserrat-text uppercase">continue reading <i class="icon ion-arrow-right-c"></i></a>
					</div>
					<!-- blog post -->
					<div class="blog_post wow fadeInUp">
						<div class="post_media">
							<iframe height="500" src="https://www.youtube.com/embed/1mO_QMYV-QE?list=PLXWu0OP8--WQZcdnx1OuIwQ2MEMT2ee8O" frameborder="0" allowfullscreen></iframe>
						</div>
						<div class="post_info">
							<div class="post_date montserrat-text uppercase">january 13, 2016</div>
							<i class="icon ion-chatbox-working"></i>
							<span>8</span>
							<i class="icon ion-ios-heart"></i>
							<span>15</span>
						</div>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
						</p>
						<a href="single-post.html" class="link montserrat-text uppercase">continue reading <i class="icon ion-arrow-right-c"></i></a>
					</div>
					<!-- blog post -->
					<div class="blog_post wow fadeInUp">
						<div class="post_media">
							<iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/51057943&amp;amp;color=ff5500&amp;amp;auto_play=false&amp;amp;hide_related=false&amp;amp;show_comments=true&amp;amp;show_user=true&amp;amp;show_reposts=false" frameborder="0"></iframe>
						</div>
						<div class="post_info">
							<div class="post_date montserrat-text uppercase">january 13, 2016</div>
							<i class="icon ion-chatbox-working"></i>
							<span>8</span>
							<i class="icon ion-ios-heart"></i>
							<span>15</span>
						</div>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
						</p>
						<a href="single-post.html" class="link montserrat-text uppercase">continue reading <i class="icon ion-arrow-right-c"></i></a>
					</div>

					<!-- pagination -->
					<div class="blog_pagination wow fadeInUp">
						<a href="" class="page">
							<i class="icon ion-arrow-left-c prev"></i>
							<span>previous</span>
						</a>
						<span class="divisor">/</span>
						<a href="" class="page">
							<span>next</span>
							<i class="icon ion-arrow-right-c next"></i>
						</a>
					</div>
				</div><!-- end col -->

				<div class="col-md-3">
					<div class="sidebar">
						<div class="widget">
							<div class="input_2">
								<input type="text" placeholder="search...">
								<button type="submit"><i class="icon ion-search"></i></button>
							</div>
						</div>
						<div class="widget">
							<div class="widget_title">posts</div>
							<div class="tab">
								<nav>
									<a href="">popular</a>
									<a href="">latest</a>
									<div class="bottom-line"></div>
								</nav>
								<div class="tab_single shown">
									<div class="related_post">
										<div class="thumb"><img src="assets/img/thumb.jpg" alt="image"></div>
										<a href="" class="post_title montserrat-text uppercase">Magna mollis ultricies</a>
										<div class="post_date">3th october 2015</div>
									</div>
									<div class="related_post">
										<div class="thumb"><img src="assets/img/thumb.jpg" alt="image"></div>
										<a href=""  class="post_title montserrat-text uppercase">Magna mollis ultricies</a>
										<div class="post_date">3th october 2015</div>
									</div>
									<div class="related_post">
										<div class="thumb"><img src="assets/img/thumb.jpg" alt="image"></div>
										<a href=""  class="post_title montserrat-text uppercase">Magna mollis ultricies</a>
										<div class="post_date">3th october 2015</div>
									</div>
								</div>
								<div class="tab_single">
									<div class="related_post">
										<div class="thumb"><img src="assets/img/thumb.jpg" alt="image"></div>
										<a href=""  class="post_title montserrat-text uppercase">Magna mollis ultricies</a>
										<div class="post_date">3th october 2015</div>
									</div>
									<div class="related_post">
										<div class="thumb"><img src="assets/img/thumb.jpg" alt="image"></div>
										<a href=""  class="post_title montserrat-text uppercase">Magna mollis ultricies</a>
										<div class="post_date">3th october 2015</div>
									</div>
									<div class="related_post">
										<div class="thumb"><img src="assets/img/thumb.jpg" alt="image"></div>
										<a href=""  class="post_title montserrat-text uppercase">Magna mollis ultricies</a>
										<div class="post_date">3th october 2015</div>
									</div>
								</div>
							</div>
						</div>

						<div class="widget wow fadeInUp">
							<div class="widget_title">categories</div>
							<ul class="list_2">
								<li><a href="">Business	<span>15</span></a></li>
								<li><a href="">Photography	<span>22</span></a></li>
								<li><a href="">Journal	<span>27</span></a></li>
								<li><a href="">Web development	<span>30</span></a></li>
							</ul>
						</div>

						<div class="widget wow fadeInUp">
							<div class="widget_title">tags cloud</div>
							<ul class="tags">
								<li><a href="">css</a></li>
								<li><a href="">html</a></li>
								<li><a href="">javascript</a></li>
								<li><a href="">jquery</a></li>
								<li><a href="">bootstrap</a></li>
								<li><a href="">web development</a></li>
								<li><a href="">ui &amp; ux</a></li>
							</ul>
						</div>

						<div class="widget wow fadeInUp">
							<div class="widget_title">instagram</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
							<div class="thumb" style="margin-bottom:15px">
								<a href=""><img src="assets/img/thumb.jpg" alt="thumb"></a>
							</div>
						</div>

						<div class="widget wow fadeInUp">
							<div class="widget_title">archives</div>
							<ul class="list_2">
								<li><a href="">Jan-Feb 2015	<span>15</span></a></li>
								<li><a href="">Feb-Mar 2015	<span>22</span></a></li>
								<li><a href="">Mar-Apr 2015	<span>27</span></a></li>
								<li><a href="">Apr-May 2015	<span>30</span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div><!-- end row -->
		</div><!-- end container -->
	</section>


	<!-- newsletter -->
	<section class="green-section wow fadeInUp" style="padding:50px 0">
		<div class="container">
			<div class="col-md-6 col-sm-12">
				<div class="row">
					<span class="white-text montserrat-text uppercase" style="font-size:30px;display:block;">
						you think we're cool? let's work together
					</span>
					<a href="#" class="btn white" style="margin-top:30px"><span>get in touch</span></a>
				</div>
			</div>

			<div class="col-md-6 col-sm-12">
				<div class="row">
					<div class="white-section" style="padding:20px">
						<span class="montserrat-text uppercase" style="font-size:24px">stay informed with our newsletter</span>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua.
						</p>
						<form action="#" method="post">
							<div class="input_1">
								<input type="text" name="email">
								<span>your email</span>
							</div>
							<button type="submit" class="btn green" style="margin-top:20px"><span>send</span></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>


	<!-- FOOTER -->
	<footer class="main-footer wow fadeInUp">
		<div class="container">
			<div class="col-md-8 col-sm-12">
				<div class="row">
					<nav class="footer-nav">
						<ul>
							<li><a href="index.html" class="animsition-link link">Home</a></li>
							<li><a href="about.html" class="animsition-link link">about us</a></li>
							<li><a href="services.html" class="animsition-link link">services</a></li>
							<li><a href="portfolio-1.html" class="animsition-link link">portfolio</a></li>
							<li><a href="blog-1.html" class="animsition-link link">blog</a></li>
							<li><a href="contact.html" class="animsition-link link">contact us</a></li>
						</ul>
					</nav>
				</div>
			</div>

			<div class="col-md-4 col-sm-12" style="text-align:right">
				<div class="row">
					<div class="uppercase gray-text">
						created by akhouad &copy;2016. all rights reserved.
					</div>
					<ul class="social-icons" style="margin-top:30px;float:right">
						<li><a href="#"><i class="icon ion-social-facebook"></i></a></li>
						<li><a href="#"><i class="icon ion-social-twitter"></i></a></li>
						<li><a href="#"><i class="icon ion-social-youtube"></i></a></li>
						<li><a href="#"><i class="icon ion-social-linkedin"></i></a></li>
						<li><a href="#"><i class="icon ion-social-pinterest"></i></a></li>
						<li><a href="#"><i class="icon ion-social-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- SCRIPTS -->
	<script type="text/javascript" src="assets/js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="assets/js/smoothScroll.js"></script>
	<script type="text/javascript" src="assets/js/jquery.animsition.min.js"></script>
	<script type="text/javascript" src="assets/js/wow.min.js"></script>
	<script type="text/javascript" src="assets/js/main.js"></script>
	<script type="text/javascript">
	$(window).load(function(){
		new WOW().init();
	});
	</script>
</body>
</html>